<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laravelista\Comments\Commentable;

class OwnChanel extends Model
{
    use Commentable; // SoftDeletes;

    protected $table = '0_OwnChanel';
	protected $primaryKey = 'id';
	
	protected $fillable =[
		'order_status',
        'region_show',
        'cust_div',
        'cust_divisi',
        'li_milestone',
        'li_product_name',
        'li_sid',
        'li_status',
        'order_created_date',
        'order_subtype',
        'price_type_cd',
        'range_duration',
        'range_umur_status',
        'segment',
        'vendor_name',
        'x_cx_termin_flg',
        'cust_segmen',
        'li_id',
        'order_id',
        'accountnas',
        'action_cd',
        'agree_createdby_name',
        'agree_end_date',
        'agree_itemnum',
        'agree_name',
        'agree_start_date',
        'agree_type',
        'agreenum',
        'agreenum_parent',
        'agrrenum_master',
        'asset_integ_id',
        'bc_date',
        'bill_profile_id',
        'bill_region',
        'bill_witel',
        'billaccntname',
        'billaccntnum',
        'billing_type_cd',
        'currency',
        'cust_region',
        'cust_witel',
        'custaccntname',
        'custaccntnum',
        'disc_amt_rc',
        'discnt_amt',
        'li_bandwidth',
        'li_billcomdate',
        'li_billdate',
        'li_billing_start_date',
        'li_created_date',
        'li_milestone_date',
        'li_monthly_price',
        'li_otc_price',
        'li_payment_term',
        'li_status_date',
        'login',
        'nipnas',
        'number_of_records',
        'order_createdby_name',
        'order_id_copy',
        'order_status_date',
        'par_order_item_id',
        'prevorder',
        'product_activation_date',
        'quote_row_id',
        'rev_num',
        'segmen_data',
        'servaccntname',
        'servaccntnum',
        'service_region',
        'service_witel',
        'tanggal_proses',
        'tgl_bilcom_alt',
        'total_price',
        'total_price_copy',
        'umur_order',
        'umur_status_order',
        'updated_date_sheet',
        'kategori_product',
        'kategori_revenue',
        'nama_cust',
        'nama_project',
        'total_price_check',
        'no_kb',
        'segmen_check',
        'product',
        'order_type',
        'witel',
        'umur_order_check',
        'order_id_check',
        'bima_nossa',
        'uic',
        'close_wfm_bima',
        'indikasi_order',
        'keterangan',
        'keterangan_detail',
        'status_order_desc',
        'kategori_status',
        'umur_order_2',
        'komitmen',
        'ket_ebis',
        'kelompok_uic',
        'date_check_col',
        'status_vlookup',
        'milestone_vlookup',
        'cek',
		];
	
	protected $dates = [
        'order_created_date',
        'agree_end_date',
        'agree_start_date',
        'bc_date',
        'li_billcomdate',
        'li_billdate',
        'li_billing_start_date',
        'li_created_date',
        'li_milestone_date',
        'li_status_date',
        'order_status_date',
        'product_activation_date',
        'tanggal_proses',
        'tgl_bilcom_alt',
        'updated_date_sheet',
        'created_at',
        'updated_at',
    ];
}